---
# These tasks installs the base system

- name: Install basic system utilities
  become: yes
  become_user: root
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - vim
    - htop
    - tmux
    - screen
    - sudo
    - xorg
    - xinit
    - lightdm
    - i3
    - python3-gi
    - gir1.2-webkit-3.0
    - libwebkitgtk-3.0-dev
    - git-core
    - python3-pip

- name: Select i3 as default window manager
  become: yes
  become_user: root
  alternatives:
    name: x-window-manager
    path: /usr/bin/i3

- name: Enable lightdm service
  become: yes
  become_user: root
  service: name=lightdm state=started enabled=yes

- name: Upload lightdm config file.
  become: yes
  become_user: root
  template: src=lightdm.conf dest=/etc/lightdm/lightdm.conf mode=0644
  notify:
    - Restart lightdm

- name: Create directory for i3 config
  become: yes
  file: path=/home/pi/.i3 state=directory owner=pi
  tags: i3

- name: Upload i3 config file.
  template: src=i3config.conf dest=/home/{{ ansible_ssh_user }}/.i3/config mode=0644
  notify:
    - Restart lightdm

- name: Download git repo
  git:
    repo: "{{ repository }}"
    dest: "{{ project_root }}"
    version: master
  args:
    accept_hostkey: yes
  notify:
        - Restart lightdm
  tags: git
  register: git

- name: Install pip requirements
  pip:
    requirements: "{{ project_root }}/requirements.txt"
    state: present
    extra_args: --user

- name: Upload config.py file.
  template: src=config.py dest=/home/{{ ansible_ssh_user }}/mqttwebview/config.py mode=0644
  notify:
    - Restart lightdm
