---
- name: Install Docker
  pacman:
    name: docker
    state: latest
    update_cache: yes
  become: yes

- name: Ensure that Docker runs
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
