---
#- name: Install Docker
#  apt:
#    name: docker
#    state: latest
#  become: yes
#
#- name: Ensure that Docker runs
#  systemd:
#    name: docker
#    state: started
#    enabled: yes
#  become: yes
  
