---
important_urls: 
    - "http://c-flo.cbrp3.c-base.org/workshop/"

urls: 
    - "https://c-beam.cbrp3.c-base.org/mechdisplay"
    - "http://c-flo.cbrp3.c-base.org/bar-status/"
    - "https://c-beam.cbrp3.c-base.org/sensors"
