---
important_urls: 
    - "https://c-beam.cbrp3.c-base.org/sensors"

urls: 
    - "http://openmct.cbrp3.c-base.org/index.html#/browse/mine/10666e49-8a01-4ff9-8189-9d67a9af780c/b358cd1c-7b59-4e84-9d8c-d1a584a9ef86"
    - "http://c-beam.cbrp3.c-base.org/events"
    - "http://openmct.cbrp3.c-base.org/index.html#/browse/mine/10666e49-8a01-4ff9-8189-9d67a9af780c/019a072e-f3ca-4d10-93d0-4027631baea6"
    - "http://c-beam.cbrp3.c-base.org/bvg"
    - "http://openmct.cbrp3.c-base.org/index.html#/browse/mine/9dc35495-7712-4ca4-a52f-3edd2dd4aced/29702b43-c34f-474f-b09c-c544a8e0a8a0"
    - "https://c-beam.cbrp3.c-base.org/reddit"
    - "http://openmct.cbrp3.c-base.org/index.html#/browse/mine/9dc35495-7712-4ca4-a52f-3edd2dd4aced/9f398f6a-5afc-4301-85f9-8d2bf03886a3"
    - "https://c-beam.cbrp3.c-base.org/weather"
