---
# Variables listed here are applicable to all host groups

ansible_ssh_private_key: deploy.pem
project_name: mqttwebview
repository: https://github.com/c-base/mqttwebview.git
email_host: c-mail.c-base.org
msgflo_role: "{{ ansible_nodename }}"
use_kiosk: true
timezone: "Europe/Berlin"
