---
# Variables listed here are applicable to only raspbian systems

ansible_ssh_user: pi
display_user: pi
project_root: /home/{{ display_user }}/mqttwebview
repository: https://github.com/c-base/mqttwebview.git
display_manager: lightdm
