---
# These tasks installs the base system

- name: Install lightdm
  become: yes
  become_user: root
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - lightdm

- name: Enable lightdm service
  become: yes
  become_user: root
  service: name=lightdm state=started enabled=yes
  tags: config

- name: Upload lightdm config file.
  become: yes
  become_user: root
  template: src=lightdm.conf dest=/etc/lightdm/lightdm.conf mode=0644
  notify:
    - Restart lightdm
  tags: config
  
- name: Create cronjob to restart lightdm
  become: yes
  become_user: root
  cron:
      name: restart mqttwebview
      weekday: "*"
      minute: 5
      hour: "*/2"
      user: root
      job: "/usr/sbin/service lightdm restart"
      cron_file: ansible_restart_mqttwebview
  tags: config