---
# This playbook deploys the whole application stack in this site.

- name: configure and deploy the webservers and application code
  hosts: raspbians
  roles:
    - raspbian
    - lightdm
    - fullscreen
    
- name: configure and deploy the webservers and application code
  hosts: lxdms
  roles:
    - raspbian
    - splitscreen