---
- name: station IoT coordinator
  hosts: msgflos
  roles:
    - role: "arch-docker"
    - role: "docker-systemd"
      container_name: "msgflo"
      container_repository: "cbase/raspberrypi3-c-flo"
      container_ports:
        - "127.0.0.1:3569:3569"
    - role: "docker-systemd"
      container_name: "msgflo-foreign"
      container_repository: "cbase/raspberrypi3-c-flo"
      container_extra_options:
        "--entrypoint npm run foreign"
      container_after: "docker.service msgflo.service"
